// Tam 5 harfli Türkçe kelimeler
const VALID_WORDS = [
  "ABONE", "ACABA", "ADANA", "ADRES", "AFYON", "AKŞAM", "ALARM", "ALTIN", "AMBAR",
  "ANANE", "ARABA", "ARMUT", "ASLAN", "ATLAS", "BAHAR", "BAKIR", "BALIK", "BANKA",
  "BARUT", "BASIN", "BATIK", "BEYAZ", "BİBER", "BİRAZ", "BOYUT", "BULUT", "BURSA",
  "CEPHE", "CEVAP", "CEVİZ", "CİHAN", "DAĞCI", "DAIRE", "DALGA", "DAMAR", "DEFNE",
  "DENİZ", "DERİN", "DEVAM", "DİLEK", "DOĞRU", "DOLAP", "DÜNYA", "DÜZEN", "EKMEK",
  "ELMAS", "ENGEL", "ERKEN", "EVRAK", "FENER", "FIRIN", "FİLİZ", "FİNCAN", "FİRMA",
  "GAZET", "GİRİŞ", "GÖLGE", "GÖREV", "GÜLÜŞ", "GÜNEŞ", "GÜVEN", "HABER", "HAKIM",
  "HALKA", "HAMAM", "HASAT", "HASTA", "HAVUZ", "HAYAT", "HAZIR", "HELVA", "HIZLI",
  "HOROZ", "HUKUK", "HURMA", "JAPON", "JETON", "JİLET", "KABUK", "KADIN", "KAFES",
  "KAHVE", "KALEM", "KAMER", "KANAL", "KAPAK", "KARAR", "KARGO", "KASAB", "KATIL",
  "KAVUN", "KAYIK", "KAZAN", "KEBAP", "KEMER", "KESİM", "KETEN", "KILIÇ", "KİTAP",
  "KIZIL", "KOLAY", "KONAK", "KÖPRÜ", "KUMAR", "KURAL", "KUTU", "LAMBA", "LİMAN",
  "LİMON", "LİSTE", "LOKUM", "MADEN", "MAKAS", "MASAL", "MAYIS", "MEKAN", "MESAJ",
  "METAL", "MEYVE", "MİMAR", "MİSIR", "MODEL", "MOTOR", "NEFES", "NİSAN", "NOTER",
  "OLGUN", "ORMAN", "OTEL", "OYUN", "ÖDEME", "ÖLÇÜ", "ÖRNEK", "PAKET", "PALTO",
  "PAMUK", "PARÇA", "PATIK", "PİLOT", "POLİS", "PROJE", "RADYO", "RAKAM", "RENK",
  "RESİM", "RİTİM", "ROBOT", "ROMAN", "SABAH", "SAHNE", "SAKIZ", "SALON", "SANAT",
  "SARAY", "SATIŞ", "SAVUN", "SEBZE", "SELAM", "SERAP", "SEVGİ", "SICAK", "SIFIR",
  "SİLAH", "SOĞUK", "SONRA", "SORGU", "STAD", "SÜRE", "ŞAPKA", "ŞEHİR", "ŞEKER",
  "ŞİFRE", "ŞİMDİ", "TABAN", "TABLO", "TAKIM", "TAMAM", "TARAF", "TARİH", "TATIL",
  "TEKER", "TEMEL", "TENİS", "TERAS", "TERZİ", "TESİS", "TOHUM", "TORBA", "TREN",
  "UÇAK", "UĞUR", "ULUS", "UMUT", "UNVAN","UYGAR", "UZMAN", "ÜCRET", "ÜRÜN", "ÜSTÜN",
  "VADİ", "VAKIT", "VATAN", "VİRAJ", "VİZE", "YABAN", "YAKIN", "YALIN", "YANAK",
  "YARIN", "YASAK", "YAVRU", "YAZAR", "YEMEK", "YEREL", "YETKİ", "YILAN", "YOLCU",
  "YORUM", "ZAMAN", "ZARAR", "ZEBRA", "ZEMİN", "ZİHİN", "ZORUN"
];
